---
title: "TG Figures"
---

Code repository for TG figures and exploratory analysis code.

## Helper functions and prep

These pages describe big scripts run over all variables and save the outputs. This means models are standardised and outputs can be pulled from the saved scripts.

Examples include:

* [correlation of variables with age at baseline](helper-corr-age-at-baseline.qmd)
* [Wilcoxon tests over all variables](helper-wilcoxon-tests.qmd)
* [linear mixed models over all variables](helper-lmm.qmd)
* [repeated measures correlation](helper-rmcorr.qmd)


## Figure and Table scripts

These pages provide the code for the final figures.

* [Figure 1: Overview](fig1-overview.qmd)
  + [Supplementary Figure 1](fig1-overview.qmd)
  + [Supplementary Figure 2](fig1-overview.qmd)
  + [Supplementary Figure 3](fig1-overview.qmd)
* [Figure 2: Clinical](fig2-clin.qmd)
  + [Supplementary Figure 4](fig2-clin.qmd)
  + [Supplementary Figure 5](fig2-clin.qmd)
  + [Supplementary Figure 1](fig2-clin.qmd)
* [Figure 3: Epigenetics](fig3-epi.qmd)
  + [Supplementary Figure 6](fig3-epi.qmd)
* [Figure 4: Immune and Metabolome](fig4-imm-metabolome.qmd)
  + [Supplementary Figure 7](fig4-imm-metabolome.qmd)
  + [Supplementary Figure 8](fig4-imm-metabolome.qmd)
  + [Supplementary Figure 9](fig4-imm-metabolome.qmd)
* [Figure 5: Microbiome](fig5-microbqmd)
  + [Supplementary Figure 10](fig5-micro.qmd)
  + [Supplementary Figure 11](fig5-micro.qmd)
* [Figure 6: MCT Effect](mct-effect.qmd)
* [Supplementary Figure 12: Menopause Effect](menopause.qmd)
+ [Supplementary Figure 13: delta BMI prediction](helper-bmi.qmd)
* [Supplementary Figure 14: Sensitivity analysis](timeSensitivity.qmd)
* [Figure 7: Integration](fig7-integration.qmd)
  + [Supplementary Figure 15](fig7-integration.qmd)
  + [Supplementary Figure 16](fig7-integration.qmd)
  + [Supplementary Figure 17](fig7-integration.qmd)

(Supplementary) Tables are contained in the table subheading.