---
title: "Delta BMI assessment (ST11)"
format:
  html:
    toc: true
    code-fold: true
    code-overflow: wrap
    code-tools: true
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = T, message = F, warning = F, eval = F)
```


```{r libs, eval = T}
library(here)
library(dplyr)
here::i_am("st11-deltaBMI.qmd")
```

Here we explore the impact of ∆ BMI on outcomes. Basic models are run including ∆ bmi as a covariate.

```{r eval = T}
load(here("out/out_lmm_factor.Rdata"))
load("src/vars.Rdata")
vars1 <- vars |> dplyr::filter(!assay %in% c("Stool microbiome: ASVs",
                                             "Saliva microbiome: ASVs",
                                             "Stool microbiome: families_clr",
                                             "Saliva microbiome: families_clr")) |> 
  dplyr::filter(x != 'ImmAge_gen_adj') |> 
  dplyr::mutate(new = paste0(assay, "_", x))

x <- out_lmm$`Basic model with BMI and BMI change` |> 
  dplyr::filter(x %in% vars1$new)

sig_bmi_delta <- x[x$p.value_dbmi < 0.05,]

source(here("src/FDRcorr.R"))
y <- FDRcorr(x)
sig_bmi_delta_adj <- y[y$p.value_dbmi_adj < 0.05,]
sig_bmi_delta_adj$p.value_dbmi_adj


out <- FDRcorr(x)

out2 <- out |> 
  dplyr::select(-starts_with("std.error_")) |> 
  dplyr::left_join(dplyr::select(vars1, assay, assay2, label, x), by = c('x' = 'x',
                                                                         'assay' = 'assay')) |> 
  plyr::mutate(variable = ifelse(!is.na(label), label, x),
                    assay = ifelse(!is.na(assay2), assay2, assay)) |> 
      dplyr::select(-any_of(c("x", "label", "assay2"))) |> 
      dplyr::mutate(across(!contains(c("variable", "assay", "group")), ~ signif(., digits = 4))) |> 
      
      dplyr::arrange(assay) |> 
      dplyr::relocate(assay, variable) |> 
      dplyr::distinct() |> 
  dplyr::select(contains(c("assay", "variable", "dbmi")))


writexl::write_xlsx(as.data.frame(out2),
                    path = paste0("out/Supplementary-Table-S11.xlsx"))

```

`r nrow(sig_bmi_delta_adj)` remain significant after FDR: `r sig_bmi_delta_adj$x`


What happens when taking time as ordinal?

```{r eval = T}
x <- out_lmm$`Basic model with BMI and BMI change - ordered`
sig_bmi_delta <- x[x$p.value_dbmi < 0.05,]
source(here("src/FDRcorr.R"))
y <- FDRcorr(x)
sig_bmi_delta_adj <- y[y$p.value_dbmi_adj < 0.05,]
```

`r nrow(sig_bmi_delta_adj)` remain significant: `r sig_bmi_delta_adj$x`